name: Deploy to Preview Channel

on:
  push:
    branches:
      - development

jobs:
  deploy_testing_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_7ED5F }}"
          projectId: portfolio-7ed5f
          channelId: testing
          expires: 1d
